"""Permission keys and default role-to-permission mappings."""

PERMISSIONS = [
    ("users:view", "View users"),
    ("users:manage", "Manage users and roles"),
    ("users:create", "Create users"),
    ("users:update", "Update users"),
    ("users:disable", "Disable users"),
    ("roles:view", "View roles and permissions"),
    ("roles:manage", "Manage role permissions"),
    ("clusters:view", "View clusters"),
    ("clusters:add", "Add clusters"),
    ("clusters:update", "Update clusters"),
    ("clusters:remove", "Remove clusters"),
    ("clusters:test", "Test cluster connections"),
    ("overview:view", "View cluster overview"),
    ("namespaces:view", "View namespaces"),
    ("resources:view", "View namespace resources"),
    ("pods:view", "View pods"),
    ("deployments:view", "View deployments"),
    ("replicasets:view", "View ReplicaSets"),
    ("statefulsets:view", "View StatefulSets"),
    ("daemonsets:view", "View DaemonSets"),
    ("jobs:view", "View Jobs"),
    ("cronjobs:view", "View CronJobs"),
    ("logs:view", "View pod logs"),
    ("alerts:view", "View alerts"),
    ("alerts:manage", "Manage alerts and notifications"),
    ("upgrades:precheck", "Run upgrade prechecks"),
    ("upgrades:start", "Start upgrade workflows"),
    ("settings:view", "View settings"),
    ("settings:manage", "Manage settings"),
    ("audit:view", "View audit logs"),
    ("services:view", "View services"),
    ("services:ports:view", "View service ports"),
    ("inventory:view", "View application inventory"),
    ("inventory:register", "Register existing applications in inventory"),
    ("inventory:update", "Update application catalog metadata"),
    ("inventory:remove", "Remove applications from inventory metadata"),
    ("apps:deploy", "Deploy applications to clusters"),
    ("apps:dryrun", "Run deployment dry-run validation"),
    ("apps:diff", "View deployment diffs"),
    ("apps:delete", "Delete applications from clusters"),
    ("helm:view", "View Helm releases"),
    ("helm:install", "Install Helm releases"),
    ("helm:upgrade", "Upgrade Helm releases"),
    ("helm:rollback", "Rollback Helm releases"),
    ("helm:uninstall", "Uninstall Helm releases"),
    ("helm:values:view", "View Helm release values"),
    ("helm:values:update", "Update Helm release values"),
    ("app_services:view", "View application services"),
    ("app_services:create", "Create application services"),
    ("app_services:update", "Update application services"),
    ("app_services:delete", "Delete application services"),
    ("clients:view", "View clients"),
    ("clients:create", "Create clients"),
    ("clients:update", "Update clients"),
    ("clients:delete", "Delete clients"),
]

ALL_PERMISSION_KEYS = [key for key, _ in PERMISSIONS]

INVENTORY_VIEW_ALIASES = ("inventory:view", "resources:view")

WORKLOAD_VIEW_PERMISSIONS = [
    "replicasets:view",
    "statefulsets:view",
    "daemonsets:view",
    "jobs:view",
    "cronjobs:view",
]

VIEWER_PERMISSIONS = [
    "clusters:view",
    "overview:view",
    "namespaces:view",
    "resources:view",
    "inventory:view",
    "pods:view",
    "deployments:view",
    *WORKLOAD_VIEW_PERMISSIONS,
    "logs:view",
    "alerts:view",
    "services:view",
    "services:ports:view",
    "helm:view",
    "app_services:view",
    "clients:view",
]

OPERATOR_PERMISSIONS = [
    "clusters:view",
    "overview:view",
    "namespaces:view",
    "resources:view",
    "inventory:view",
    "inventory:register",
    "apps:dryrun",
    "apps:diff",
    "helm:view",
    "pods:view",
    "deployments:view",
    *WORKLOAD_VIEW_PERMISSIONS,
    "logs:view",
    "alerts:view",
    "alerts:manage",
    "upgrades:precheck",
    "services:view",
    "services:ports:view",
    "app_services:view",
    "app_services:create",
    "app_services:update",
    "clients:view",
    "clients:create",
    "clients:update",
]

CLUSTER_ADMIN_PERMISSIONS = [
    "clusters:view",
    "overview:view",
    "namespaces:view",
    "resources:view",
    "inventory:view",
    "inventory:register",
    "inventory:update",
    "inventory:remove",
    "apps:deploy",
    "apps:dryrun",
    "apps:diff",
    "helm:view",
    "helm:install",
    "helm:upgrade",
    "helm:rollback",
    "helm:values:view",
    "helm:values:update",
    "pods:view",
    "deployments:view",
    *WORKLOAD_VIEW_PERMISSIONS,
    "logs:view",
    "alerts:view",
    "alerts:manage",
    "upgrades:precheck",
    "services:view",
    "services:ports:view",
    "app_services:view",
    "app_services:create",
    "app_services:update",
    "app_services:delete",
    "clients:view",
    "clients:create",
    "clients:update",
    "clients:delete",
]

ROLE_DEFINITIONS = {
    "admin": {
        "description": "Full access to everything",
        "is_system_role": True,
        "permissions": ALL_PERMISSION_KEYS,
    },
    "operator": {
        "description": "Operate clusters, alerts, and upgrade prechecks",
        "is_system_role": True,
        "permissions": OPERATOR_PERMISSIONS,
    },
    "cluster_admin": {
        "description": "Manage inventory catalog and deploy applications",
        "is_system_role": True,
        "permissions": CLUSTER_ADMIN_PERMISSIONS,
    },
    "viewer": {
        "description": "Read-only access to allowed clusters and namespaces",
        "is_system_role": True,
        "permissions": VIEWER_PERMISSIONS,
    },
}

DEFAULT_USERS = [
    {
        "username": "admin",
        "password": "admin123",
        "email": "admin@kubesight.local",
        "full_name": "Cluster Admin",
        "role": "admin",
    },
    {
        "username": "viewer",
        "password": "viewer123",
        "email": "viewer@kubesight.local",
        "full_name": "Read Only User",
        "role": "viewer",
    },
    {
        "username": "operator",
        "password": "operator123",
        "email": "operator@kubesight.local",
        "full_name": "Platform Operator",
        "role": "operator",
    },
]
