apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubesight-application-intelligence-artifacts
  namespace: kubesight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
