apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesight-backend
  namespace: kubesight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesight-backend
  template:
    metadata:
      labels:
        app: kubesight-backend
    spec:
      serviceAccountName: kubesight-backend
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend

          image: registry.areeba.com/kubesight-backend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: kubesight-config
            - secretRef:
                name: kubesight-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 1Gi
      
      
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kubesight
spec:
  type: ClusterIP
  selector:
    app: kubesight-backend
  ports:
    - port: 5000
      targetPort: 5000

