"""
Regenerate the self-hosted font set in src/assets/fonts and src/styles/fonts.css.

Google serves a different stylesheet per user agent. Asking with a modern
Chrome UA gets woff2 with unicode-range split by subset, which is what we
want: the browser downloads latin only unless a page actually uses latin-ext.

Run from frontend/:  python scripts/fetch-fonts.py
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONT_DIR = os.path.join(ROOT, "src", "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "src", "styles", "fonts.css")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

# family -> (google name, slug, weights)
FAMILIES = [
    ("Instrument Sans", "instrument", [400, 500, 600, 700]),
    ("Archivo", "archivo", [400, 500, 600, 700, 800]),
    ("JetBrains Mono", "jbmono", [400, 500, 600, 700]),
]

# Only these subsets ship. Anything else in the stylesheet is dropped.
KEEP = {"latin": "latin", "latin-ext": "latin-ext"}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def blocks(css):
    """Split a Google stylesheet into (comment_subset, block_text) pairs."""
    out = []
    subset = None
    for chunk in re.split(r"(/\*\s*[a-z0-9-]+\s*\*/)", css):
        m = re.match(r"/\*\s*([a-z0-9-]+)\s*\*/", chunk.strip())
        if m:
            subset = m.group(1)
            continue
        if "@font-face" in chunk and subset:
            out.append((subset, chunk))
    return out


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    pieces = []
    pieces.append("/* Self-hosted fonts, generated by scripts/fetch-fonts.py. */\n")
    pieces.append("/* Families: Instrument Sans (UI), Archivo (display), "
                  "JetBrains Mono (data). Subsets: latin, latin-ext. */\n")

    for name, slug, weights in FAMILIES:
        q = name.replace(" ", "+")
        url = ("https://fonts.googleapis.com/css2?family=%s:wght@%s&display=swap"
               % (q, ";".join(str(w) for w in weights)))
        css = fetch(url).decode("utf-8")

        # Google hands the same variable woff2 back for every weight in the
        # query, labelled once per weight. Group by (subset, source url) so a
        # variable family ships ONE file carrying a weight range, instead of
        # eight byte-identical copies of it.
        groups = {}
        for subset, block in blocks(css):
            if subset not in KEEP:
                continue
            wm = re.search(r"font-weight:\s*([\d\s]+?);", block)
            um = re.search(r"unicode-range:\s*([^;]+);", block)
            sm = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not (wm and um and sm):
                continue
            ws = [int(x) for x in wm.group(1).split()]
            if len(ws) == 1 and ws[0] not in weights:
                continue
            key = (subset, sm.group(1))
            g = groups.setdefault(key, {"w": [], "range": um.group(1).strip()})
            g["w"].extend(ws)

        got = 0
        for (subset, src), g in groups.items():
            lo, hi = min(g["w"]), max(g["w"])
            wspec = str(lo) if lo == hi else "%d %d" % (lo, hi)
            fname = ("%s-%s-%s.woff2" % (slug, "var", KEEP[subset]) if lo != hi
                     else "%s-%d-%s.woff2" % (slug, lo, KEEP[subset]))
            path = os.path.join(FONT_DIR, fname)
            if not os.path.exists(path):
                with open(path, "wb") as fh:
                    fh.write(fetch(src))
            um_range = g["range"]
            pieces.append(
                "/* %s %s, %s */\n"
                "@font-face {\n"
                "  font-family: '%s';\n"
                "  font-style: normal;\n"
                "  font-weight: %s;\n"
                "  font-display: swap;\n"
                "  src: url('../assets/fonts/%s') format('woff2');\n"
                "  unicode-range: %s;\n"
                "}\n" % (name, wspec, KEEP[subset], name, wspec, fname,
                         um_range)
            )
            got += 1
        print("%-16s %d faces" % (name, got))
        if not got:
            sys.exit("no faces parsed for %s" % name)

    with open(CSS_OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(pieces))
    print("wrote", os.path.relpath(CSS_OUT, ROOT))


if __name__ == "__main__":
    main()
