{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubesight.fullname" . }}-default-deny
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubesight.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubesight.fullname" . }}-ingress
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [{{ include "kubesight.name" . }}]
      - key: app.kubernetes.io/instance
        operator: In
        values: [{{ .Release.Name }}]
      - key: app.kubernetes.io/component
        operator: In
        values: [web, frontend]
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressPodSelector | nindent 12 }}
      ports:
        - {protocol: TCP, port: 5000}
        - {protocol: TCP, port: 8080}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubesight.fullname" . }}-egress
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubesight.selectorLabels" . | nindent 6 }}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - {protocol: TCP, port: 5432}
        - {protocol: TCP, port: 6379}
    {{- with .Values.networkPolicy.kubernetesApiEgress }}
    {{- if .enabled }}
    - to:
        {{- range .cidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        {{- range .ports }}
        - {protocol: TCP, port: {{ . }}}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- range .Values.networkPolicy.externalEgress }}
    - to:
        - ipBlock:
            cidr: {{ .cidr | quote }}
            {{- with .except }}
            except: {{ toJson . }}
            {{- end }}
      {{- with .ports }}
      ports:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

