{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubesight.fullname" . }}-observer
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces, nodes, pods, pods/log, services, endpoints, events, configmaps, persistentvolumeclaims, persistentvolumes]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: [get, list, watch]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings, clusterroles, clusterrolebindings]
    verbs: [get, list, watch]
  - apiGroups: [metrics.k8s.io]
    resources: [nodes, pods]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubesight.fullname" . }}-observer
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubesight.fullname" . }}-observer
subjects:
  - kind: ServiceAccount
    name: {{ include "kubesight.serviceAccountName" (dict "root" . "component" "web") }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.worker.enabled }}
  - kind: ServiceAccount
    name: {{ include "kubesight.serviceAccountName" (dict "root" . "component" "worker") }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}

