{{- if .Values.serviceAccounts.create }}
{{- range $component := list "web" "worker" "scheduler" "frontend" }}
{{- if or (eq $component "web") (eq $component "frontend") (and (eq $component "worker") $.Values.worker.enabled) (and (eq $component "scheduler") $.Values.scheduler.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubesight.serviceAccountName" (dict "root" $ "component" $component) }}
  labels:
    {{- include "kubesight.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  {{- with $.Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ if or (eq $component "web") (eq $component "worker") }}true{{ else }}false{{ end }}
{{- end }}
{{- end }}
{{- end }}

