{{- if eq .Values.deploymentMode "trial" }}
{{- $name := include "kubesight.secretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $dbPassword := randAlphaNum 40 -}}
{{- $jwtSecret := randAlphaNum 64 -}}
{{- $encryptionSecret := randAlphaNum 64 -}}
{{- $redisPassword := randAlphaNum 40 -}}
{{- if $existing }}
{{- $dbPassword = index $existing.data "POSTGRES_PASSWORD" | b64dec -}}
{{- $jwtSecret = index $existing.data "JWT_SECRET_KEY" | b64dec -}}
{{- $encryptionSecret = index $existing.data "ALERT_ROUTING_SECRET_KEY" | b64dec -}}
{{- $redisPassword = index $existing.data "REDIS_PASSWORD" | b64dec -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $dbPassword | quote }}
  REDIS_PASSWORD: {{ $redisPassword | quote }}
  DATABASE_URL: {{ printf "postgresql://kubesight:%s@%s-postgresql:5432/kubesight" $dbPassword (include "kubesight.fullname" .) | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s-redis:6379/0" $redisPassword (include "kubesight.fullname" .) | quote }}
  JWT_SECRET_KEY: {{ $jwtSecret | quote }}
  ALERT_ROUTING_SECRET_KEY: {{ $encryptionSecret | quote }}
{{- end }}
