import { hasAnyClusterAccess, hasAnyNamespaceAccess, isAdminUser } from "../utils/authz.js";

const SOURCE_LABELS = {
  cpu_usage_vs_limit: "CPU usage exceeded the configured threshold.",
  alert_policy: "Generated by a cluster alert policy.",
  mock_data: "Demo alerts for this environment.",
  filtered: "Alerts are limited to your assigned clusters and resources.",
  rbac: "Alerts are limited to your assigned clusters and resources.",
  none: "No live alert source is available for this cluster right now.",
};

export function formatAlertSource(meta = {}, { isAdmin = false } = {}) {
  const source = String(meta.source || "").trim();
  if (!source) {
    return "";
  }
  if (isAdmin) {
    const threshold = meta.thresholdPercent;
    if (threshold != null && source === "cpu_usage_vs_limit") {
      return `Source: ${source} (threshold ${threshold}%)`;
    }
    return `Source: ${source}`;
  }
  return SOURCE_LABELS[source] || "Alert generated from cluster monitoring.";
}

export function formatAlertTime(value) {
  if (!value) {
    return "—";
  }
  try {
    return new Date(value).toLocaleString();
  } catch {
    return String(value);
  }
}

export function getAlertResourceName(alert) {
  return alert?.pod || alert?.resourceName || alert?.resource || "—";
}

export function getAlertPolicyLabel(alert) {
  if (alert?.source === "alert_policy" && alert?.policyName) {
    return alert.policyName;
  }
  return alert?.policyName || "—";
}

export function getAlertTypeLabel(alert) {
  const type = alert?.alertType || "metric";
  return type === "log" ? "Log" : "Metric";
}

export function isLogAlert(alert) {
  return alert?.alertType === "log";
}

export function formatTriggeredConditions(alert) {
  if (isLogAlert(alert)) {
    return alert?.matchedPattern ? `Pattern: ${alert.matchedPattern}` : alert?.description || "—";
  }
  const conditions = alert?.triggeredConditions;
  if (!Array.isArray(conditions) || !conditions.length) {
    return alert?.description || "—";
  }
  return conditions
    .filter((item) => item?.matched !== false)
    .map((item) => {
      const label = item.metricLabel || item.metricKey || "metric";
      const observed = item.observedValue != null ? ` (observed ${item.observedValue})` : "";
      return `${label} ${item.operator || ""} ${item.threshold ?? ""}${observed}`.trim();
    })
    .join("; ");
}

export function buildAlertsScopeSummary({
  clusterId,
  clusters = [],
  namespaces = [],
  resources = {},
}) {
  const cluster = clusters.find((item) => item.id === clusterId);
  const namespaceNames = namespaces.map((ns) => ns?.name || ns).filter(Boolean);
  const resourceNames = (resources.pods || [])
    .map((pod) => pod?.name)
    .filter(Boolean)
    .sort();

  return {
    clusterLabel: cluster?.name || clusterId || "—",
    clusterId: clusterId || "",
    namespaces: namespaceNames,
    resources: resourceNames,
  };
}

export function hasAlertMonitoringScope({
  hasClusters,
  namespaces = [],
  resources = {},
  user,
}) {
  if (!hasClusters) {
    return false;
  }
  if ((resources.pods || []).length > 0) {
    return true;
  }
  if (namespaces.length > 0) {
    return true;
  }
  if (user && isAdminUser(user)) {
    return true;
  }
  if (user && (hasAnyNamespaceAccess(user) || hasAnyClusterAccess(user))) {
    return true;
  }
  return false;
}
